# Generated by Django 4.2.7 on 2025-10-27 06:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique short code for the URL",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        help_text="The original URL to be shortened",
                        max_length=2048,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="When true, requires authentication token to access",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the short URL has been accessed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the short URL was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the short URL was last updated",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner of the short URL",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Short URL",
                "verbose_name_plural": "Short URLs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="URLVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of the visitor"),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string (browser/device info)"
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the URL was accessed",
                    ),
                ),
                (
                    "short_url",
                    models.ForeignKey(
                        help_text="The short URL that was visited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="urlshortener.shorturl",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who accessed the URL (if authenticated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="url_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "URL Visit",
                "verbose_name_plural": "URL Visits",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["short_url", "-accessed_at"],
                        name="urlshortene_short_u_a589a5_idx",
                    ),
                    models.Index(
                        fields=["user", "-accessed_at"],
                        name="urlshortene_user_id_10df40_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="shorturl",
            index=models.Index(
                fields=["short_code"], name="urlshortene_short_c_d81072_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shorturl",
            index=models.Index(
                fields=["owner", "-created_at"], name="urlshortene_owner_i_35c8bb_idx"
            ),
        ),
    ]
